spring:
  config:
    activate:
      on-profile: prod # 'prod' 프로파일이 활성화될 때 이 설정을 사용합니다
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    main-db:
      jdbc-url: jdbc:mysql://${MAIN_DB_HOST_NAME}/${MAIN_DB_STORAGE_NAME}
      username: ${MAIN_DB_USERNAME}
      password: ${MAIN_DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
    stat-db:
      jdbc-url: jdbc:mysql://${STAT_DB_HOST_NAME}/${STAT_DB_STORAGE_NAME}
      username: ${STAT_DB_USERNAME}
      password: ${STAT_DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
  data:
    redis:
      host: ${REDIS_HOST_NAME}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      port: 6379
  jwt:
    auth-secret: ${JWT_AUTH_SECRET_KEY}# JWT 비밀 키
    token-secret: ${JWT_TOKEN_SECRET_KEY}

server:
  port: 8080
#  ssl:
#    key-alias: tomcat
#    key-store: classpath:keystore.p12
#    key-store-type: PKCS12
#    key-store-password: ${KEY_STORE_PASSWORD}
#    key-store-provider: SunJSSE
#    #trust-store: classpath:truststore.jks
#    #trust-store-password: ${TRUST_STORE_PASSWORD}
#  http2:
#    enabled: true
#  error:
#    include-message: always
#    include-stacktrace: never

monitoring:
  loki:
    url: http://loki:3100/loki/api/v1/push
