spring:
  data:
    redis:
      host: ${REDIS_HOST_NAME} # 배포 후에는 변경해야함
      port: 6379
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    maindb:
      jdbc-url: jdbc:mysql://${MAIN_DB_HOST_NAME}/${MAIN_DB_STORAGE_NAME}
      username: ${MAIN_DB_USERNAME}
      password: ${MAIN_DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

    statdb:
      jdbc-url: jdbc:mysql://${STAT_DB_HOST_NAME}/${STAT_DB_STORAGE_NAME}
      username: ${STAT_DB_USERNAME}
      password: ${STAT_DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

  jwt:
    secret: 1o23eoi21joiejoijsdoijoisdjfojafa

server:
  port: 8080

