filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/rest/**/*.log
    fields:
      application: rest
    fields_under_root: true
    multiline:
      pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      negate: true
      match: after
  - type: log
    enabled: true
    paths:
      - /logs/collector/**/*.log
    fields:
      application: collector
    fields_under_root: true
    multiline:
      pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      negate: true
      match: after
  - type: log
    enabled: true
    paths:
      - /logs/hub/**/*.log
    fields:
      application: hub
    fields_under_root: true
    multiline:
      pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      negate: true
      match: after
  - type: log
    enabled: true
    paths:
      - /logs/batch/**/*.log
    fields:
      application: batch
    fields_under_root: true
    multiline:
      pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      negate: true
      match: after
  - type: log
    enabled: true
    paths:
      - /logs/emulator/**/*.log
    fields:
      application: emulator
    fields_under_root: true
    multiline:
      pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      negate: true
      match: after

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info