spring:
  config:
    activate:
      on-profile: prod
  rabbitmq:
    host: ${MQ_HOST_NAME}
    port: 5672
    username: ${MQ_USERNAME}
    password: ${MQ_PASSWORD}

  jwt:
    token-secret: ${JWT_TOKEN_SECRET_KEY}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active}

monitoring:
  loki:
    host: ${LOKI_HOST}
    post: ${LOKI_PORT}
    endpoint: ${LOKI_ENDPOINT}
  logstash:
    host: ${LOGSTASH_HOST}
    port: ${LOGSTASH_PORT}
