spring:
  config:
    activate:
      on-profile: prod
  rabbitmq:
    host: ${MQ_HOST_NAME}
    port: 5672
    username: ${MQ_USERNAME}
    password: ${MQ_PASSWORD}

  jwt:
    token-secret: ${JWT_TOKEN_SECRET_KEY}

server:
  port: 8085

monitoring:
  loki:
    url: http://loki:3100/loki/api/v1/push
