services:

  # ELK Stack
  elasticsearch:
    image: elasticsearch:8.12.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=wherecar-es-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: 2500M
        reservations:
          memory: 1500M
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - where-car-network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.1
    platform: linux/arm64
    container_name: logstash
    restart: unless-stopped
    volumes:
      - ./config/logstash/pipeline:/usr/share/logstash/pipeline
      - ./config/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ../logs:/logs:ro
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - "LS_JAVA_OPTS=-Xms512m -Xmx512m"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 800M
        reservations:
          memory: 600M
    ports:
      - "5044:5044"
      - "5001:5000/tcp"
      - "5001:5000/udp"
      - "9600:9600"
    networks:
      - where-car-network
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:8.12.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
      - ELASTICSEARCH_USERNAME=${KIBANA_USERNAME}
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 768M
        reservations:
          memory: 384M
    networks:
      - where-car-network
    depends_on:
      - elasticsearch

  # Grafana Loki stack
  prometheus:
    image: prom/prometheus:v2.49.0
    container_name: prometheus
    ports:
      - "9090:9090"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 1500M
        reservations:
          memory: 750M
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - where-car-network
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 512M
        reservations:
          memory: 256M
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yml
    volumes:
      - loki-data:/loki
      - ./config/loki:/etc/loki
    networks:
      - where-car-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.3.3
    container_name: grafana
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 800M
        reservations:
          memory: 400M
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - where-car-network
    restart: unless-stopped
    depends_on:
      - prometheus
      - loki
      - elasticsearch

networks:
  where-car-network:
    driver: bridge

volumes:
  elasticsearch-data:
    driver: local
  grafana-storage:
    driver: local
  prometheus-data:
    driver: local
  loki-data: # 추가
    driver: local
