spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8095
  ssl:
    key-alias: tomcat
    key-store: classpath:keystore-deploy.p12
    key-store-type: PKCS12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-provider: SunJSSE
  http2:
    enabled: true
  error:
    include-message: always
    include-stacktrace: never

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active}
  prometheus:
    metrics:
      export:
        enabled: true

emulator:
  # 디바이스 관련 설정
  device:
    mdn: ${DEVICE_MDN:01234567890}
    vrp: ${DEVICE_VRP:12가3456}
    gpx-file: ${DEVICE_GPX_FILE:gwangju-to-muju_formatted.gpx}
  storage:
    db-file: ${DEVICE_STORAGE_FILE:device_db.json}
  # API 엔드포인트 설정
  endpoints:
    # 인증 서비스
    rest:
      base-url: http://localhost:8080
      token-path: /api/emulator/token
    # 허브 서비스 설정
    hub:
      base-url: http://localhost:8085
      on-path: /api/hub/on
      cycle-info-path: /api/hub/gps
      off-path: /api/hub/off

monitoring:
  loki:
    url: ${LOKI_URL}
