spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8095

wherecar:
  device:
    mdn: 01234567890
    vrp: 34가5678
  db:
    storage-file-name: device_db.json
  api:
    rest:
      url: http://localhost:8080
      token:
        endpoint: /emulator/token
    collector:
      url: http://localhost:8090
    hub:
      url: http://localhost:8090 # TODO: 실제로는 허브로 주기및 시동 정보를 보내야 함!
      event:
        start-endpoint: /api/on
        cycle-endpoint: /api/gps
        stop-endpoint: /api/off
