spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8090

wherecar:
  device:
    mdn: 01234567890
    vrp: 34가5678
  db:
    storage-file-name: device_db.json
  api:
    rest:
      url: http://localhost:8080
    collector:
      url: http://localhost:8090
    hub:
      url: http://localhost:8085
