spring:
  application:
    name: emulator
  thymeleaf: # 기능 테스트를 위한 타임리프 사용
    check-template-location: false # 타임리프 검사 비활성화

  profiles:
    default: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active}
  prometheus:
    metrics:
      export:
        enabled: true