spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8090

wherecar:
  server:
    url: http://localhost:8080
  emulator:
    car-mdn: 01234567890
    car-vrp: 12가3456
  db:
    file-name: device_db.json
