global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'wherecar-rest'
    metrics_path: '/actuator/prometheus'
    scheme: 'https'
    static_configs:
      - targets: [ 'api.where-car.com:8080' ]
        labels:
          instance: 'rest-api'
          env: 'prod'

  - job_name: 'wherecar-hub'
    metrics_path: '/actuator/prometheus'
    scheme: 'https'
    static_configs:
      - targets: [ 'hub.where-car.com:8080' ]
        labels:
          instance: 'hub-server'

  - job_name: 'wherecar-batch'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'
    static_configs:
      - targets: [ 'batch.where-car.com:8080' ]
        labels:
          instance: 'batch-server'

  - job_name: 'wherecar-collector'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'
    static_configs:
      - targets: [ 'collector.where-car.com:8080' ]
        labels:
          instance: 'collector-server'

  - job_name: 'rabbitmq'
    scheme: 'http'
    static_configs:
      - targets: ['mq.where-car.com:15692']