spring:
  config:
    activate:
      on-profile: dev # 'dev' 프로파일이 활성화될 때 이 설정을 사용합니다.
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${DB_HOST_NAME}/${DB_STORAGE_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  rabbitmq:
    host: ${MQ_HOST_NAME}
    port: 5672
    username: ${MQ_USERNAME}
    password: ${MQ_PASSWORD}
    virtual-host: /

server:
  port: 8090
