input {
  beats {
    port => 5044
    tags => ["filebeat"]
  }

  tcp {
    port => 5045
    codec => json_lines
    tags => ["direct"]
  }
}

filter {

  if [application] {
    mutate {
      add_field => { "[@metadata][app]" => "%{[application]}" }
      add_tag => ["%{[application]}-service"]
    }
  }
  else {
    mutate {
      add_field => { "[@metadata][app]" => "unknown" }
    }
  }

  if [environment] {
    mutate {
      add_field => { "[@metadata][env]" => "%{[environment]}" }
    }
  }
  else {
    mutate {
      add_field => { "[@metadata][env]" => "default" }
    }
  }

  if [level] == "ERROR" {
    mutate {
      add_tag => ["error"]
    }
  }
  else if [level] == "WARN" {
    mutate {
      add_tag => ["warning"]
    }
  }

}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "%{[@metadata][app]}-%{[@metadata][env]}-%{+YYYY.MM.dd}"
    retry_initial_interval => 2
    retry_max_interval => 64
    timeout => 30
  }
}
